# Jihad Shehadeh G00986964
# CS 262, Lab Section 212
# Lab 7 
# The compiler: gcc for C programs, g++ for C++ programs, etc

CC = gcc

CFLAGS=-g -Wall

TARGET = lab7_jshehad_212

all = ${TARGET}

${TARGET}: ${TARGET}.c
	${CC} ${CFLAGS} -o ${TARGET} ${TARGET}.c -pedantic-errors

clean:
	rm ${TARGET}
