# Jihad Shehadeh G00986964
# CS 262, Lab Section 212
# Lab 6 
# The compiler: gcc for C programs, g++ for C++ programs, etc

CC = gcc

CFLAGS=-g -Wall

TARGET = lab6_jshehad_212

all = ${TARGET}

${TARGET}: ${TARGET}.c
	${CC} ${CFLAGS} -o ${TARGET} ${TARGET}.c

clean:
	rm ${TARGET}
